/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardStudioRouteImport } from './routes/dashboard.studio'
import { Route as DashboardPrecificacaoRouteImport } from './routes/dashboard.precificacao'
import { Route as DashboardPlanoRouteImport } from './routes/dashboard.plano'
import { Route as DashboardConfiguracoesRouteImport } from './routes/dashboard.configuracoes'
import { Route as DashboardCarrosseisRouteImport } from './routes/dashboard.carrosseis'
import { Route as AprovarTokenRouteImport } from './routes/aprovar.$token'
import { Route as DashboardClientesIndexRouteImport } from './routes/dashboard.clientes.index'
import { Route as DashboardClientesIdRouteImport } from './routes/dashboard.clientes.$id'
import { Route as DashboardClientesIdIndexRouteImport } from './routes/dashboard.clientes.$id.index'
import { Route as DashboardClientesIdPrecificacaoRouteImport } from './routes/dashboard.clientes.$id.precificacao'
import { Route as DashboardClientesIdConteudosRouteImport } from './routes/dashboard.clientes.$id.conteudos'
import { Route as DashboardClientesIdBriefingRouteImport } from './routes/dashboard.clientes.$id.briefing'
import { Route as DashboardClientesIdAprovacaoRouteImport } from './routes/dashboard.clientes.$id.aprovacao'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudioRoute = DashboardStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPrecificacaoRoute = DashboardPrecificacaoRouteImport.update({
  id: '/precificacao',
  path: '/precificacao',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlanoRoute = DashboardPlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfiguracoesRoute = DashboardConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCarrosseisRoute = DashboardCarrosseisRouteImport.update({
  id: '/carrosseis',
  path: '/carrosseis',
  getParentRoute: () => DashboardRoute,
} as any)
const AprovarTokenRoute = AprovarTokenRouteImport.update({
  id: '/aprovar/$token',
  path: '/aprovar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardClientesIndexRoute = DashboardClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientesIdRoute = DashboardClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientesIdIndexRoute =
  DashboardClientesIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardClientesIdRoute,
  } as any)
const DashboardClientesIdPrecificacaoRoute =
  DashboardClientesIdPrecificacaoRouteImport.update({
    id: '/precificacao',
    path: '/precificacao',
    getParentRoute: () => DashboardClientesIdRoute,
  } as any)
const DashboardClientesIdConteudosRoute =
  DashboardClientesIdConteudosRouteImport.update({
    id: '/conteudos',
    path: '/conteudos',
    getParentRoute: () => DashboardClientesIdRoute,
  } as any)
const DashboardClientesIdBriefingRoute =
  DashboardClientesIdBriefingRouteImport.update({
    id: '/briefing',
    path: '/briefing',
    getParentRoute: () => DashboardClientesIdRoute,
  } as any)
const DashboardClientesIdAprovacaoRoute =
  DashboardClientesIdAprovacaoRouteImport.update({
    id: '/aprovacao',
    path: '/aprovacao',
    getParentRoute: () => DashboardClientesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRoute
  '/aprovar/$token': typeof AprovarTokenRoute
  '/dashboard/carrosseis': typeof DashboardCarrosseisRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/plano': typeof DashboardPlanoRoute
  '/dashboard/precificacao': typeof DashboardPrecificacaoRoute
  '/dashboard/studio': typeof DashboardStudioRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/clientes/$id': typeof DashboardClientesIdRouteWithChildren
  '/dashboard/clientes/': typeof DashboardClientesIndexRoute
  '/dashboard/clientes/$id/aprovacao': typeof DashboardClientesIdAprovacaoRoute
  '/dashboard/clientes/$id/briefing': typeof DashboardClientesIdBriefingRoute
  '/dashboard/clientes/$id/conteudos': typeof DashboardClientesIdConteudosRoute
  '/dashboard/clientes/$id/precificacao': typeof DashboardClientesIdPrecificacaoRoute
  '/dashboard/clientes/$id/': typeof DashboardClientesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRoute
  '/aprovar/$token': typeof AprovarTokenRoute
  '/dashboard/carrosseis': typeof DashboardCarrosseisRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/plano': typeof DashboardPlanoRoute
  '/dashboard/precificacao': typeof DashboardPrecificacaoRoute
  '/dashboard/studio': typeof DashboardStudioRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/clientes': typeof DashboardClientesIndexRoute
  '/dashboard/clientes/$id/aprovacao': typeof DashboardClientesIdAprovacaoRoute
  '/dashboard/clientes/$id/briefing': typeof DashboardClientesIdBriefingRoute
  '/dashboard/clientes/$id/conteudos': typeof DashboardClientesIdConteudosRoute
  '/dashboard/clientes/$id/precificacao': typeof DashboardClientesIdPrecificacaoRoute
  '/dashboard/clientes/$id': typeof DashboardClientesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRoute
  '/aprovar/$token': typeof AprovarTokenRoute
  '/dashboard/carrosseis': typeof DashboardCarrosseisRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/plano': typeof DashboardPlanoRoute
  '/dashboard/precificacao': typeof DashboardPrecificacaoRoute
  '/dashboard/studio': typeof DashboardStudioRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/clientes/$id': typeof DashboardClientesIdRouteWithChildren
  '/dashboard/clientes/': typeof DashboardClientesIndexRoute
  '/dashboard/clientes/$id/aprovacao': typeof DashboardClientesIdAprovacaoRoute
  '/dashboard/clientes/$id/briefing': typeof DashboardClientesIdBriefingRoute
  '/dashboard/clientes/$id/conteudos': typeof DashboardClientesIdConteudosRoute
  '/dashboard/clientes/$id/precificacao': typeof DashboardClientesIdPrecificacaoRoute
  '/dashboard/clientes/$id/': typeof DashboardClientesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/design-system'
    | '/login'
    | '/aprovar/$token'
    | '/dashboard/carrosseis'
    | '/dashboard/configuracoes'
    | '/dashboard/plano'
    | '/dashboard/precificacao'
    | '/dashboard/studio'
    | '/dashboard/'
    | '/dashboard/clientes/$id'
    | '/dashboard/clientes/'
    | '/dashboard/clientes/$id/aprovacao'
    | '/dashboard/clientes/$id/briefing'
    | '/dashboard/clientes/$id/conteudos'
    | '/dashboard/clientes/$id/precificacao'
    | '/dashboard/clientes/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design-system'
    | '/login'
    | '/aprovar/$token'
    | '/dashboard/carrosseis'
    | '/dashboard/configuracoes'
    | '/dashboard/plano'
    | '/dashboard/precificacao'
    | '/dashboard/studio'
    | '/dashboard'
    | '/dashboard/clientes'
    | '/dashboard/clientes/$id/aprovacao'
    | '/dashboard/clientes/$id/briefing'
    | '/dashboard/clientes/$id/conteudos'
    | '/dashboard/clientes/$id/precificacao'
    | '/dashboard/clientes/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/design-system'
    | '/login'
    | '/aprovar/$token'
    | '/dashboard/carrosseis'
    | '/dashboard/configuracoes'
    | '/dashboard/plano'
    | '/dashboard/precificacao'
    | '/dashboard/studio'
    | '/dashboard/'
    | '/dashboard/clientes/$id'
    | '/dashboard/clientes/'
    | '/dashboard/clientes/$id/aprovacao'
    | '/dashboard/clientes/$id/briefing'
    | '/dashboard/clientes/$id/conteudos'
    | '/dashboard/clientes/$id/precificacao'
    | '/dashboard/clientes/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DesignSystemRoute: typeof DesignSystemRoute
  LoginRoute: typeof LoginRoute
  AprovarTokenRoute: typeof AprovarTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/studio': {
      id: '/dashboard/studio'
      path: '/studio'
      fullPath: '/dashboard/studio'
      preLoaderRoute: typeof DashboardStudioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/precificacao': {
      id: '/dashboard/precificacao'
      path: '/precificacao'
      fullPath: '/dashboard/precificacao'
      preLoaderRoute: typeof DashboardPrecificacaoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/plano': {
      id: '/dashboard/plano'
      path: '/plano'
      fullPath: '/dashboard/plano'
      preLoaderRoute: typeof DashboardPlanoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/configuracoes': {
      id: '/dashboard/configuracoes'
      path: '/configuracoes'
      fullPath: '/dashboard/configuracoes'
      preLoaderRoute: typeof DashboardConfiguracoesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/carrosseis': {
      id: '/dashboard/carrosseis'
      path: '/carrosseis'
      fullPath: '/dashboard/carrosseis'
      preLoaderRoute: typeof DashboardCarrosseisRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/aprovar/$token': {
      id: '/aprovar/$token'
      path: '/aprovar/$token'
      fullPath: '/aprovar/$token'
      preLoaderRoute: typeof AprovarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/clientes/': {
      id: '/dashboard/clientes/'
      path: '/clientes'
      fullPath: '/dashboard/clientes/'
      preLoaderRoute: typeof DashboardClientesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clientes/$id': {
      id: '/dashboard/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/dashboard/clientes/$id'
      preLoaderRoute: typeof DashboardClientesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clientes/$id/': {
      id: '/dashboard/clientes/$id/'
      path: '/'
      fullPath: '/dashboard/clientes/$id/'
      preLoaderRoute: typeof DashboardClientesIdIndexRouteImport
      parentRoute: typeof DashboardClientesIdRoute
    }
    '/dashboard/clientes/$id/precificacao': {
      id: '/dashboard/clientes/$id/precificacao'
      path: '/precificacao'
      fullPath: '/dashboard/clientes/$id/precificacao'
      preLoaderRoute: typeof DashboardClientesIdPrecificacaoRouteImport
      parentRoute: typeof DashboardClientesIdRoute
    }
    '/dashboard/clientes/$id/conteudos': {
      id: '/dashboard/clientes/$id/conteudos'
      path: '/conteudos'
      fullPath: '/dashboard/clientes/$id/conteudos'
      preLoaderRoute: typeof DashboardClientesIdConteudosRouteImport
      parentRoute: typeof DashboardClientesIdRoute
    }
    '/dashboard/clientes/$id/briefing': {
      id: '/dashboard/clientes/$id/briefing'
      path: '/briefing'
      fullPath: '/dashboard/clientes/$id/briefing'
      preLoaderRoute: typeof DashboardClientesIdBriefingRouteImport
      parentRoute: typeof DashboardClientesIdRoute
    }
    '/dashboard/clientes/$id/aprovacao': {
      id: '/dashboard/clientes/$id/aprovacao'
      path: '/aprovacao'
      fullPath: '/dashboard/clientes/$id/aprovacao'
      preLoaderRoute: typeof DashboardClientesIdAprovacaoRouteImport
      parentRoute: typeof DashboardClientesIdRoute
    }
  }
}

interface DashboardClientesIdRouteChildren {
  DashboardClientesIdAprovacaoRoute: typeof DashboardClientesIdAprovacaoRoute
  DashboardClientesIdBriefingRoute: typeof DashboardClientesIdBriefingRoute
  DashboardClientesIdConteudosRoute: typeof DashboardClientesIdConteudosRoute
  DashboardClientesIdPrecificacaoRoute: typeof DashboardClientesIdPrecificacaoRoute
  DashboardClientesIdIndexRoute: typeof DashboardClientesIdIndexRoute
}

const DashboardClientesIdRouteChildren: DashboardClientesIdRouteChildren = {
  DashboardClientesIdAprovacaoRoute: DashboardClientesIdAprovacaoRoute,
  DashboardClientesIdBriefingRoute: DashboardClientesIdBriefingRoute,
  DashboardClientesIdConteudosRoute: DashboardClientesIdConteudosRoute,
  DashboardClientesIdPrecificacaoRoute: DashboardClientesIdPrecificacaoRoute,
  DashboardClientesIdIndexRoute: DashboardClientesIdIndexRoute,
}

const DashboardClientesIdRouteWithChildren =
  DashboardClientesIdRoute._addFileChildren(DashboardClientesIdRouteChildren)

interface DashboardRouteChildren {
  DashboardCarrosseisRoute: typeof DashboardCarrosseisRoute
  DashboardConfiguracoesRoute: typeof DashboardConfiguracoesRoute
  DashboardPlanoRoute: typeof DashboardPlanoRoute
  DashboardPrecificacaoRoute: typeof DashboardPrecificacaoRoute
  DashboardStudioRoute: typeof DashboardStudioRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardClientesIdRoute: typeof DashboardClientesIdRouteWithChildren
  DashboardClientesIndexRoute: typeof DashboardClientesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCarrosseisRoute: DashboardCarrosseisRoute,
  DashboardConfiguracoesRoute: DashboardConfiguracoesRoute,
  DashboardPlanoRoute: DashboardPlanoRoute,
  DashboardPrecificacaoRoute: DashboardPrecificacaoRoute,
  DashboardStudioRoute: DashboardStudioRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardClientesIdRoute: DashboardClientesIdRouteWithChildren,
  DashboardClientesIndexRoute: DashboardClientesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DesignSystemRoute: DesignSystemRoute,
  LoginRoute: LoginRoute,
  AprovarTokenRoute: AprovarTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
